name = "kyste-tickets-api"
main = "index.js"
compatibility_date = "2024-01-01"

# KV — uniquement pour les sessions Discord (très léger)
[[kv_namespaces]]
binding = "KYSTE_KV"
id      = "96e078c10620442dbb59e5ec46da87f4"

# Variables en clair
[vars]
DISCORD_GUILD_ID = "1463607904069357699"
DASHBOARD_URL    = "https://kystedashboard.netlify.app/"
API_URL          = "https://kyste-ticket-api.onrender.com"

# Secrets (wrangler secret put NOM  ou dashboard CF)
# DISCORD_CLIENT_ID
# DISCORD_CLIENT_SECRET
# DISCORD_BOT_TOKEN
